language: python
cache: pip
sudo: false

matrix:
    include:
    - python: "3.4"
      addons:
        apt:
            packages: 
            - liblapack-dev 
                
    - python: "3.5"

install:
    - pip install .

# run tests
script:
    - cd tests 
    - py.test
