language: python
cache: pip
sudo: true
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq liblapack3 liblapack-dev

install:
  - pip install .[dev]
  - pip install git+https://gitlab.kwant-project.org/cwg/wraparound.git

script:
  - cd tests
  - py.test

jobs:
  include:
    - stage: compliance
      script: pre-commit run --all-files

stages:
  - compliance
  - test
