language: python
sudo: true
python:
    - "3.4"
    - "3.5"

before_install:
    - sudp apt-get update -qq
    - sudo apt-get install -qq liblapack.so 

install:
    - pip install .

# run tests
script:
    - cd tests 
    - py.test
