language: python
cache: pip
sudo: true
python:
    - "3.4"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq liblapack.so 
    - sudo apt-get install -qq libblas.so 

install:
    - pip install .[kwant]
    - pip install git+https://gitlab.kwant-project.org/cwg/wraparound.git

# run tests
script:
    - cd tests 
    - py.test
