language: python
python:
    - "3.4"
    - "3.5"

virtualenv:
    - system_site_packages: true
    
before_install:
    - apt-get install python3-numpy
    - apt-get install python3-scipy

install:
    - pip install .

# run tests
script:
    - cd tests 
    - py.test
