language: python
python:
    - python: "3.4"
      env: DEPS="libgfortran=1.0 numpy scipy matplotlib"
    - python: "3.5"
      env: DEPS="numpy scipy matplotlib"

install:
  - pip install .

# run tests
script:
  - cd tests 
  - py.test
