language: python
cache: pip
sudo: false
matrix:
    include:
    - python: "3.4"
      addons:
        apt:
            packages: 
            - liblapack.so 
                
    - python: "3.5"
#~ python:

#~ before_install:
    #~ - sudo apt-get update -qq
    #~ - sudo apt-get install -qq liblapack.so 

install:
    - pip install .

# run tests
script:
    - cd tests 
    - py.test
